version: "3.7"

services:

  db:
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: generalsw
      MARIADB_DATABASE: ob
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"